apiVersion: v1
kind: Pod
metadata:
  name: stress
  namespace: nvidia-gpu-operator
spec:
  containers:
    - name: stress
      image: ghcr.io/chipzoller/stress:0.1
      command:
      - python3
      - /usr/src/app/stress_gpu.py
      args:
        - --gpus=1
        - --utilization=40
      resources:
        limits:
          nvidia.com/gpu: 1
