apiVersion: v1
kind: ResourceQuota
metadata:
  name: gpu-operator-quota
  namespace: nvidia-device-plugin
spec:
  hard:
    pods: 100
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
        - system-node-critical
        - system-cluster-critical