# https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/feature-overview.html#cuda-test-generator-dcgmproftester
# dcgmproftester12 is capable of generating load tests for most profiling metrics (DCGM_FI_PROF_*), which are those in the range 1000-1075).
# Not all profiling metrics appear to have supported tests.
# -t flag has the field ID for the metric to be tested. See https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/feature-overview.html#profiling-metrics
# Ex., 1004 is DCGM_FI_PROF_PIPE_TENSOR_ACTIVE; 1001 is DCGM_FI_PROF_GR_ENGINE_ACTIVE
# -d flag is the duration of the test (in seconds).
apiVersion: v1
kind: Pod
metadata:
  name: dcgmproftester
spec:
  restartPolicy: OnFailure
  containers:
  - name: dcgmproftester12
    image: nvcr.io/nvidia/cloud-native/dcgm:3.3.6-1-ubuntu22.04
    command: ["/usr/bin/dcgmproftester12"]
    args: ["--no-dcgm-validation", "-t 1001", "-d 10"] 
    resources:
      limits:
        nvidia.com/gpu: 1
    securityContext:
      capabilities:
        add: ["SYS_ADMIN"]