apiVersion: apps/v1
kind: Deployment
metadata:
  name: nbody
  namespace: gputesting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nbody
  template:
    metadata:
      labels:
        app: nbody
    spec:
      # hostPID: true # required for MPS on GKE
      containers:
        - name: nbody
          image: nvcr.io/nvidia/k8s/cuda-sample:nbody
          # command: ["nbody"]
          args: ["-benchmark", "-i=100000000"]
          resources:
            limits:
              nvidia.com/gpu: 1
              # nvidia.com/gpu.shared: 1
