# N-Body simulation. See https://developer.nvidia.com/gpugems/gpugems3/part-v-physics-simulation/chapter-31-fast-n-body-simulation-cuda
# -i flag (integer) for number of iterations.
# -numdevices flag (integer) for number of GPUs to consume.
# Pod completion will show benchmarks to stdout.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcon-ai
  namespace: cz-gpu-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falcon-ai
  template:
    metadata:
      labels:
        app: falcon-ai
    spec:
      # hostPID: true # required for MPS on GKE
      containers:
        - name: pytorch-ai
          image: nvcr.io/nvidia/k8s/cuda-sample:nbody
          # command: ["nbody"]
          args: ["-benchmark", "-i=100000000", "-numdevices=1"]
          resources:
            limits:
              nvidia.com/gpu: 2
              # nvidia.com/gpu.shared: 1
