# N-Body simulation. See https://developer.nvidia.com/gpugems/gpugems3/part-v-physics-simulation/chapter-31-fast-n-body-simulation-cuda
# -i flag (integer) for number of iterations.
# -numdevices flag (integer) for number of GPUs to consume.
# Pod completion will show benchmarks to stdout.
apiVersion: v1
kind: Pod
metadata:
  name: nbody
  # namespace: cz-gpu-testing
spec:
  restartPolicy: OnFailure
  containers:
    - name: nbody
      image: nvcr.io/nvidia/k8s/cuda-sample:nbody
      args: ["-benchmark", "-numdevices=1", "-i=10000000"]
      resources:
        limits:
          nvidia.com/gpu: 1
          # nvidia.com/gpu.shared: 1
  nodeSelector:
    cloud.google.com/gke-accelerator: nvidia-tesla-a100