apiVersion: v1
kind: Pod
metadata:
  name: nvidia-tf-notebook
  namespace: cz-gpu-testing
  labels:
    app: nvidia-tf-notebook
spec:
  securityContext:
    fsGroup: 0
  containers:
  - name: nvidia-tf-notebook
    image: nvcr.io/nvidia/tensorflow:24.09-tf2-py3
    resources:
      limits:
        nvidia.com/gpu: 1
    command:
      - jupyter
      - notebook
      - --notebook-dir=/workspace
      - --ip=0.0.0.0
      - --no-browser
      - --allow-root
    ports:
    - containerPort: 8888
      name: notebook