apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi
spec:
  hostPID: true
  restartPolicy: Never
  containers:
    - name: smi
      image: docker.io/nvidia/cuda:12.5.0-runtime-ubuntu22.04
      command:
        # - nvidia-smi
        # - -L
        - sleep
        - infinity
      securityContext:
        privileged: true
      # resources:
      #   limits:
      #     nvidia.com/gpu: 1
          # nvidia.com/gpu.shared: 1
  nodeSelector:
    feature.node.kubernetes.io/pci-10de.present: "true"